"""rename descricao to codigo_setor in setores

Revision ID: 0ff35b6e04aa
Revises: 43380e398fee
Create Date: 2026-03-10 15:06:18.064541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff35b6e04aa'
down_revision: Union[str, Sequence[str], None] = '43380e398fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setores', sa.Column('codigo_setor', sa.String(length=10), nullable=True))
    op.alter_column('setores', 'nome',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_unique_constraint(None, 'setores', ['codigo_setor'])
    op.drop_column('setores', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setores', sa.Column('descricao', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'setores', type_='unique')
    op.alter_column('setores', 'nome',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('setores', 'codigo_setor')
    # ### end Alembic commands ###
