"""Create funcoes table

Revision ID: 43380e398fee
Revises: 9f2dc6177ee5
Create Date: 2026-03-10 13:48:09.449934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43380e398fee'
down_revision: Union[str, Sequence[str], None] = '9f2dc6177ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_funcao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('pin', sa.String(length=10), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('funcao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcao_id'], ['funcoes.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('operadores')
    op.alter_column('setores', 'nome',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('setores', 'descricao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'setores', ['descricao'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'setores', type_='unique')
    op.alter_column('setores', 'descricao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('setores', 'nome',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.create_table('operadores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.Column('funcao', sa.VARCHAR(length=60), nullable=False),
    sa.Column('setor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usuarios')
    op.drop_table('funcoes')
    # ### end Alembic commands ###
