"""torna setor_id e funcao_id opcionais

Revision ID: ac633c74c5c5
Revises: 283662ecd34d
Create Date: 2026-04-11 18:05:41.687542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac633c74c5c5'
down_revision: Union[str, Sequence[str], None] = '283662ecd34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'setor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuarios', 'funcao_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'funcao_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuarios', 'setor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
